### ISSUE TITLE
inverse of bread matrix - divide by # units?

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#16]
I think you've avoided dividing by the number of i.i.d. units (`n`) since it works out that the estimated sandwich variance is something like `vcov = n^(-1) * solve(A/n) %*% B/n %*% t(solve(A/n)) = (n^2)/(n^2) * solve(A) %*% B %*% t(solve(A))`. 

is there a situation in which `solve(A/n)` would work but `solve(A)` would run into any problems i.e. when `n` is very large? probably not, right? Would it be worthwhile to add the two extra lines to properly divide by `n` in all cases?

**Comment by bsaul** [comment]
> is there a situation in which solve(A/n) would work but solve(A) would run into problems

It seems like the other way would could be just as likely to need to numeric problem: the elements of A/n could be small when n is large.

Do you have an example of either situation causing a problem?

**Comment by bsaul** [comment]
Oops the previous commit, should reference #17, thought I guess this issue is also relevant.

**Comment by BarkleyBG** [comment]
re: "_Do you have an example of either situation causing a problem?_" - I might, but it could be related to another issue. I'll post when i've determined it.

**Comment by bsaul** [comment]
Closing this issue until an example can be produced.
