### ISSUE TITLE
redundant matrix inversion when computing sigma

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#17]
Seems like there's avoidable redundancy if `Ainv <- solve(A)` is defined and then `Ainv %*% B %*% t(Ainv)` is computed in `compute_sigma()`. 

I can PR this if you'd like

Also, notational trifles related to #16: isn't this sandwich calculation equal to the Sigma divided by N, where N is the number of units, and Sigma is the asymptotic variance of `sqrt(N)(theta_hat - theta)`?

**Comment by bsaul** [comment]
Yes. Thanks. I’ve removed the redundancy in the latest commit (a13d00e). 

Yes, this calculation computes Sigma/N.

**Comment by bsaul** [comment]
a13d00e
