### ISSUE TITLE
geex logos

### ISSUE THREAD

**Issue by bsaul** [bsaul/geex#25]
![geex-icon-pocket](https://user-images.githubusercontent.com/4882990/28182161-30ff8246-67d9-11e7-802d-655cc27785cf.png)
![geex-icon-text](https://user-images.githubusercontent.com/4882990/28182164-33609bc4-67d9-11e7-88ca-df99691ed854.png)
![geex-icon-horiz](https://user-images.githubusercontent.com/4882990/28182166-35ab0b1c-67d9-11e7-89e7-81a511cf175c.png)

Get it? or "Git" it?

**Comment by BarkleyBG** [comment]
what, no hex sticker?

**Comment by bsaul** [comment]
Well, its not part of the tidyverse.

**Comment by BarkleyBG** [comment]
Not _yet_!

Thought: Make the `x` in geex look like a sandwich.

**Comment by bsaul** [comment]
More: 
![geex-icon-text2](https://user-images.githubusercontent.com/4882990/28184278-bcb4be80-67e0-11e7-80ec-697d34ee806f.png)
![geex-icon-text3](https://user-images.githubusercontent.com/4882990/28184280-bf8b6d8e-67e0-11e7-8c5e-52ad449b04d4.png)
