### ISSUE TITLE
exact argument matching for numDeriv's jacobian function in compute matrices

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#27]
In the `numDeriv` v 2016.8-1 that I have installed, the `jacobian()` function takes first argument `func` not `fun`. 

Unless that argument's name has changed since 2014, I think geex relies on inexact matching of arguments in the `compute_matrices` function. 

I've opened #26 to change this one line, but  I'm leaving this issue open, because

1. You should verify whether exact argument matching already happens
2. If you accept the PR, you'll also need to change the documentation related to specifying a different `derivFUN`

**Comment by bsaul** [comment]
Thanks for finding and fixing this.
