### ISSUE TITLE
Check possible lazy eval issue with R < 3.2

### ISSUE THREAD

**Issue by bsaul** [bsaul/geex#30]
Per @BarkleyBG, a possible issue with older R version within the `create_psi` function:

> https://cran.r-project.org/bin/windows/base/old/3.2.0/NEWS.R-3.2.0.html
> Higher order functions such as the apply functions and Reduce() now force arguments to the functions they apply in order to eliminate undesirable interactions between lazy evaluation and variable capture in closures. This resolves PR#16093.
>  
> As Duncan Murdoch and Duncan Temple Lang point out   on this thread, it’s NOT a bug. It’s simply undesirable, which is why it was changed.
> https://stat.ethz.ch/pipermail/r-devel/2015-February/070686.html
>  
> Perhaps you could test some geex stuff on an earlier version of R (<3.2) and see if it happens? If it’s an issue there, then perhaps you can require R greater than 3.2?

**Comment by bsaul** [comment]
possible solution.

Within `create_psi`, change:
```
  out <- lapply(splitdt, function(data_i){
    do.call(eeFUN, args = append(list(data = data_i), outer_eeargs))
  })
```

to:
```
  out <- lapply(splitdt, function(data_i){
    force(data_i)
    do.call(eeFUN, args = append(list(data = data_i), outer_eeargs))
  })
```

**Comment by BarkleyBG** [comment]
You may not need to do this in the first place:
```
 out <- lapply(splitdt, function(data_i){
    do.call(eeFUN, args = append(list(data = data_i), outer_eeargs))
  })
``` 
seems equivalent to 
```
out <- lapply(splitdt, function(data_i){
    my_list <- list(data = data_i)
    my_new_list <- append(my_list, outer_eeargs)
    do.call(eeFUN, args = my_new_list)
})
```
and it may be that creating `my_list` is enough to force non-lazy evaluation of the `data_i` argument.

**Comment by BarkleyBG** [comment]
Do you need to require R 3.3++ or just 3.2++?

**Comment by bsaul** [comment]
The package was developed on 3.3+, so that's what I'm currently requiring.
