### ISSUE TITLE
Redundant @data and @split_data slots in m_estimation_basis

### ISSUE THREAD

**Issue by bsaul** [bsaul/geex#32]
Currently, on the develop branch, an m_estimation_basis object contains both @data and @split_data which is redundant. What's a better way? The only place where @split_data is needed is in `create_psiFUN_list`. I'm thinking of just doing the `split` operation within that function so that (essentially) two copies of the data aren't carried around.

**Comment by BarkleyBG** [comment]
Do you have any downstream calculations that use `@data` instead of `@split_data` ? Do you plan to? I assume no and no

**Comment by bsaul** [comment]
No, I think it will be clean. Once the data is "used" in creating the list of psiFUNs, it's not needed downstream.
