### ISSUE TITLE
Cleanup suggestions

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#34]
I'll suggest you move `m_estimate()` into its own file. As it is, it's not clear from looking at the filenames that it would be in `estimate_funs.R` (especially since it's at the bottom of the file). I also like it when the 'main' function has its own file. Of course, this is all personal preference.

Unrelated, do you know why you should/should not include the `geex.Rproj` file in this repo? I suppose it's helpful, but I haven't read anything one way or the other.

**Comment by bsaul** [comment]
One reason to include the .Rproj file is that if you don't, then if you pull the repo from github, then you won't have an .Rproj file. Then you'll have to create another .Rproj file. I find it easier just to keep it there and not gitignore it.
