### ISSUE TITLE
feature: grab_data_structures()

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#40]
the functions `grab_psiFUN()` use some nice programming that I think could be valuable if exported on their own. For example, the `grab_psiFUN.glm()` reads:
```

grab_psiFUN_glm <- function(object, data, weights = 1, ...){

  X  <- stats::model.matrix(object$formula, data = data)
  Y  <- as.numeric(stats::model.frame(geex::grab_response_formula(object), data = data)[[1]])
  # etc
  invlnk <- object$family$linkinv
  family_link <- paste(family, link, sep = '_')

  function(theta){
     # blah blah
  }
}
```

The part I'm interested in is the data structures that this function computes from a glm object, e.g. here `X`, `Y`, `family`, `link`, `invlnk`, etc. 

In creating a new estimating equation that involves computations that follow after fitting a glm model, I need these pieces of information. Since geex already has a way of grabbing them, i think it would make sense to functionize that process for modularity.

Thoughts? I think `grab_data_structures.*()` would be a great set of exported functions. I'd be happy to help.

**Comment by bsaul** [comment]
Do the existing grab_** functions (grab_design_matrix, grab_response, etc) not suffice?

Are you suggesting grab_model_data() to wrap all these into one?

**Comment by BarkleyBG** [comment]
> Do the existing grab_** functions (grab_design_matrix, grab_response, etc) not suffice?

I think we can do better. Perhaps the issue is that they're buried inside a closure? I think they may be helpful to access outside of the closure, too.

Here's the [causal example from the website](https://bsaul.github.io/geex/articles/v06_causal_example.html)

```
eefun <- function(data, model, alpha){
  X <- model.matrix(model, data = data)
  A <- model.response(model.frame(model, data = data))
  Y <- data$Y
  
  function(theta){
    p  <- length(theta)
    p1 <- length(coef(model))
    lp  <- X %*% theta[1:p1]
    rho <- plogis(lp)

    hh  <- ((rho/alpha)^A * ((1-rho)/(1-alpha))^(1 - A)) 
    IPW <- 1/(exp(sum(log(hh))))

    score_eqns <- apply(X, 2, function(x) sum((A - rho) * x))
    ce0 <- mean(Y * (A == 0)) * IPW / (1 - alpha)
    ce1 <- mean(Y * (A == 1)) * IPW / (alpha)
    
    c(score_eqns,
      ce0 - theta[p - 1],
      ce1 - theta[p])
  }
}
```

This works for when the model is `mglm <- glm(A ~ X1, data = vaccinesim, family = binomial)` but would require different code when the model is, say, a `glmer` object. Instead, what about this code, which would likely be much easier to adapt for programmatic use for more than one type of model object?


```
eefun <- function(data, model, alpha){
  Y <- data$Y 

  model_data <- grab_model_data(model)
  ## just a little more standardized
  X <- model_data$model_matrix
  A <- model_data$model_response

  
  function(theta){
    p  <- length(theta)
    p1 <- length(coef(model))
    lp  <- X %*% theta[1:p1] 
    ### here too, perhaps
    rho <-model_data$linkinv(lp)
    #rho <- plogis(lp)

    ### etc ###
    score_eqns <- apply(X, 2, function(x) sum((A - rho) * x))
    c(score_eqns,
       ce0 - theta[p - 1],
       ce1 - theta[p])
  }
}
```

A couple notes:

    1. the `grab_psiFUN()` was not used here. it could be though. It would replace the `apply` call in the assignment of `score_eqns`.
    2. If the `grab_psiFUN()` was used here, it would serve a different purpose than `grab_model_data()`. 
            a. Currently  `grab_psiFUN()` is useful for the estimating equations for the model parameters (here, the scores). 
            b. but `grab_model_data()` would be helpful in programmatically creating tools from `geex`.

The example above may not be the best illustration of what could be gained by the new functionality. But I think the point is that the user who wants to create custom estimating functions that use models for which `grab_psiFUN` is already created would benefit from `grab_model_data`.

**Comment by bsaul** [comment]
I think I’m missing something. Why not just rewrite the example estFUN as?

```
eefun <- function(data, model, alpha){
  X <- grab_design_matrix(data = data, grab_fixed_formula(model))
  A <- grab_response(data = data, grab_response_formula(model)) 
  Y <- grab_response(Y ~ 1, data = data)
  
  function(theta){
    p  <- length(theta)
    p1 <- length(coef(model))
    lp  <- X %*% theta[1:p1]
    rho <- plogis(lp)

    hh  <- ((rho/alpha)^A * ((1-rho)/(1-alpha))^(1 - A)) 
    IPW <- 1/(exp(sum(log(hh))))

    score_eqns <- apply(X, 2, function(x) sum((A - rho) * x))
    ce0 <- mean(Y * (A == 0)) * IPW / (1 - alpha)
    ce1 <- mean(Y * (A == 1)) * IPW / (alpha)
    
    c(score_eqns,
      ce0 - theta[p - 1],
      ce1 - theta[p])
  }
}
```

**Comment by BarkleyBG** [comment]
Hm. You're probably right in this case. I'll keep working on my use case and see if it leads me to strengthen my original position or not. 

Thanks for looking at this!
