### ISSUE TITLE
model matrix and grab_psiFun can drop columns when subsetting data by rows

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#41]
This is a particularly important issue when using `grab_psiFUN()` within an eeFun.

What (i think) happens is that when passing a subset (by row) of the data to `grab_psiFun()`, then its underlying call to `model.matrix()` can drop some levels of the factor variables if they are not present in the data's subset. This is an issue when the model parameters have fixed length (`p`): when the non-present factor levels are dropped from model.matrix such that `ncol(xmatrix)<p`, then `xmatrix %*% fixed_effects` will throw an error.

I'll have PR soon that hopefully fixes this.

**Comment by bsaul** [comment]
@BarkleyBG: This is fixed by #42, correct?

**Comment by BarkleyBG** [comment]
Yes; see the changes to `binomial_integrand()` in lines 211-218ish in  https://github.com/bsaul/geex/pull/42/commits/9c92b029d9a381321bb2013124bb2250c2d78aa0#diff-9e7756340614e55abd7d5a7348b1c746

**Comment by bsaul** [comment]
Great. Closing issue.
Thanks!
