### ISSUE TITLE
Consider units=NA for i.i.d. data?

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#6]
Users may have i.i.d. data, and no identifying variable for each row in their `data.frame`. If they do, I think `estimate_equations()` requires the users to add a column with a unique identifier for each row and to specify that column name to the `units` argument.

A possible enhancement might be to allow the user to specify `units=NA` or `NULL` or even `NA_character_`, and then `geex` would create this column for them. 

Of course, there may be downsides in this enhancement, as it may create interesting bugs.

**Comment by bsaul** [comment]
I think the thing to do is treat each row as the unit by default, but offer a message that says 'units argument is unspecified, treating each row as analysis units.' Or something like that.

This brings up a related point of how to handle missing data. Right now, missing data will generally be a problem.

**Comment by BarkleyBG** [comment]
I don't know if offering a message is a better idea than throwing an error in the case when `units` is left unspecified. 

- On one hand, it would be nice to assume that unspecified `units` means that the user has i.i.d. data. This would be (much) less irritating on the user's end. 
- On the other hand, perhaps throwing a quick error with a polite message to `"specify units=NA for i.i.d. data"` would reduce the risk of misuse.

**Comment by bsaul** [comment]
I think defaulting to `units = NA` is fine, but I think there should be a console message when users do this. How's that sound?

**Comment by BarkleyBG** [comment]
Sure! I would recommend that `units` doesn't have a default value though.
