### ISSUE TITLE
include split data and verbose messages in `estimate_equations()` output

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#8]
I recommend you add another element to the list output from `estimate_equations()`. Currently, output is `parameters`, `vcov`, `corrections`. I think another element containing all non-important information from `rootsolver`, `numDeriv::jacobian()` and other functions should be added. 

Also, perhaps add the split data to the output.

**Comment by bsaul** [comment]
I'm not finding the commit that added most of this information to the results of estimate_equations, but `estimate_equations` (after v0.2.0) contains quite a bit of information. I'd eventually like to clean up the output even more and make it an S3 class.
